CREATE TABLE ROLES
(
ID_ROL INTEGER PRIMARY KEY,
DESCRIPCION VARCHAR(50)
) ;

CREATE TABLE USUARIO
(
ID_USUARIO INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOMBRE VARCHAR(70) NOT NULL,
APELLIDOS VARCHAR(120),
PASSWORD VARCHAR(150),
DOMICILIO VARCHAR(150),
CIUDAD VARCHAR(120),
NACIMIENTO DATE,
GENERO CHAR(1) NOT NULL CHECK (GENERO IN ('H','M')),
EMAIL VARCHAR(120) NOT NULL UNIQUE,
ROL INTEGER REFERENCES ROLES(ID_ROL)
) ;


CREATE TABLE EVENTO
(
ID_EVENTO INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITULO VARCHAR(70) NOT NULL,
FECHA DATE,
FECHARES DATE,
COSTE INT,
AFORO INT,
ENTRADAS INT,
ASIENTOSFIJOS CHAR(1) NOT NULL CHECK (ASIENTOSFIJOS IN ('S','N')),
NUMFILAS INT,
NUMASIENTOSPORFILA INT,
ID_CREADOR INTEGER REFERENCES USUARIO(ID_USUARIO)
) ;

CREATE TABLE USUARIO_INSCRITO
(
ID_EVENTO INTEGER REFERENCES EVENTO(ID_EVENTO),
ID_USUARIO INTEGER REFERENCES USUARIO(ID_USUARIO),
PRIMARY KEY (ID_EVENTO, ID_USUARIO)
);

CREATE TABLE ESTUDIO
(
ID_ESTUDIO INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)
) ;

CREATE TABLE CONVERSACION
(
ID_CONVERSACION INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_USUARIO1 INTEGER NOT NULL REFERENCES USUARIO(ID_USUARIO),
ID_USUARIO2 INTEGER NOT NULL REFERENCES USUARIO(ID_USUARIO)
) ;

CREATE TABLE MENSAJE
(
ID_MENSAJE INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_CONVERSACION INTEGER REFERENCES CONVERSACION(ID_CONVERSACION),
ID_USUARIO INTEGER NOT NULL REFERENCES USUARIO(ID_USUARIO),
HORA INTEGER,
MINUTO INTEGER,
MENSAJE VARCHAR(1000),
FECHA DATE
) ;


INSERT INTO ROLES (ID_ROL, DESCRIPCION) VALUES
	(1, 'Creador de eventos'),
	(2, 'Administrador del sistema'),
	(3, 'Usuario de eventos'),
	(4, 'Teleoperador'),
	(5, 'Analista de eventos');
